src/controllers/postsController.js, src/middlewares/validateSchema.js, src/repositories/postRepository.js, src/routers/postsRouter.js, src/schemas/postSchema.js
Bom dia, Grupo!
Foi desenvolvido a rota /post/create
Foram adicionadas
- Pastas de Schema, com schema de post
- Middleware para validação de Schemas genéricos
- Criado um Repositório para Posts, sendo duas funções 'searchUser' e 'insertPost'
- E em controller a criação de um post
- Por fim foram adicionadas ao Router
Se houver algum erro de código ou de estrutura, pode mandar o feedback!
Valeu!
=> feat: create new post

src/controllers/postsController.js, src/repositories/postRepository.js, src/repositories/usersRepository.js, src/schemas/postSchema.js
Completei a rota, fazendo a validação de post do usuário conforme o token que é carregado em headers authorization.
Além disso, alterei o searchUser (é um repository) de PostRepository para UserRepository.
Também fiz uma alteração no schema. 
Com isso a rota está finalizada.
=> feat: Using information of token to post

src/controllers/hashtagController.js, src/repositories/hashtagRepository.js, src/routers/hashtagsRouter.js
Feat:
Adicionei a HashtagByName como solicitado no meu card.
=> feat: add getHashtagByName

src/controllers/likesController.js, src/repositories/likeRepository.js, src/repositories/postRepository.js, src/routers/index.js, src/routers/likesRouter.js
Agora é possível dar likes.
Fiz de uma maneira que em apenas uma rota é possível tanto adicionar o like quanto tirar o like.
Sendo assim, existem duas possibilidades.
Por favor, validem se está correto. Ou se pode haver uma maneira melhor para realizar essa função.
Qualquer feedback é muito bem vindo!
=> Likes branch

src/schemas/postSchema.js
Troquei a validação do Joi para permitir que description seja nulo.
=> fix: description can be null

src/controllers/postsController.js, src/repositories/hashtagRepository.js
deletando relacionamento entre post e hashtag
=> deletando relacionamento entre post e hashtag

src/controllers/postsController.js, src/repositories/hashtagRepository.js
Feats:
Fiz a edição do post com hashtags agora
Também corrigi o create Post
=> feat: create and update done with fixes on bug of unique hashtag name

src/controllers/postsController.js, src/repositories/likeRepository.js
Feat:
Adicionei algumas linhas para que fosse possível deletar o Post. Ele estava crashando por causa da table Likes.
=> feat: fix deletePost because of error of table likes

src/controllers/commentsController.js, src/repositories/commentRepository.js, src/routers/commentsRouter.js, src/schemas/commentSchema.js
Agora é possível inserir comentários ao banco de dados.
=> feat: insertComments

src/config/tables.sql, src/controllers/sharesController.js, src/repositories/sharesRepository.js, src/routers/index.js, src/routers/sharesRouter.js
Feat:
- Inicio do Share 
- Atualização das tabelas no SQL
=> feat: start of back of shares table

src/controllers/commentsController.js, src/repositories/commentRepository.js, src/routers/commentsRouter.js
Agora é possível acessar os comentários de um determinado post
=> feat: search Comments from post

src/repositories/commentRepository.js
Tava sem [] na hora de bsucar a query.
=> fix: commentRepository without protection

src/repositories/commentRepository.js
=> fix: Again withou $1

src/repositories/postRepository.js
Troquei o Likes total nessa query para comments total
=> feat: likesTotal to commentsTotal

src/repositories/hashtagRepository.js
Arrumei o problema de não aparecer a contagem de comentários em hashtags.
=> fix: Hashtag comment now count

src/controllers/followerController.js, src/repositories/followRepository.js, src/routers/followerRouter.js, src/routers/index.js
feature de seguir e deixa r de seguir usuarios
=> adicionando feature de seguir e deixa de seguir usuarios

src/controllers/commentsController.js
=> fix: logical of following or not

src/controllers/postsController.js, src/repositories/commentRepository.js, src/repositories/sharesRepository.js
Fix:
Arrumei o delete post que não estava funcionando por causa das novas tables
=> fix: fixed delete post with new tables

src/repositories/usersRepository.js
Fix:
- Arrumei a query do searchUsers
=> fix: search without multiple same accounts

src/controllers/postsController.js, src/repositories/postRepository.js
Mexi nas queries da timeline e de userPage
=> New timeline for share
